package main

import (
	"log"
	"net/http"
	"uptime-monitor/routes"
	"uptime-monitor/storage"

	"github.com/go-chi/chi/v5"
	_ "uptime-monitor/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	db := storage.InitDatabase()
	defer db.Close()

	r := chi.NewRouter()

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("Welcome to the Uptime Monitor API!"))
	})

	// Register all route groups
	routes.RegisterAllRoutes(r, db)

	r.Get("/swagger/*", httpSwagger.WrapHandler)

	log.Println("Server running on http://localhost:8080")
	log.Fatal(http.ListenAndServe(":8080", r))
}
