package main

import (
	"log"
	"net/http"
	"time"
	"uptime-monitor/repository"
	"uptime-monitor/routes"
	"uptime-monitor/service"
	"uptime-monitor/storage"

	_ "uptime-monitor/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	db := storage.InitDatabase()
	defer db.Close()

	r := chi.NewRouter()

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("Welcome to the Uptime Monitor API!"))
	})

	// Register all route groups
	routes.RegisterAllRoutes(r, db)
	r.Get("/swagger/*", httpSwagger.WrapHandler)

	// Start the uptime checker service
	// This service will periodically check the uptime of all targets
	// and log the results.
	targetRepo := repository.NewTargetRepository(db)
	logRepo := repository.NewTargetLogRepository(db)
	eventSvc := service.NewEventService()

	uptimeChecker := service.NewUptimeCheckerService(
		targetRepo,
		logRepo,
		eventSvc,
		time.Minute,
	)
	uptimeChecker.Start()

	log.Println("Server running on http://localhost:8080")
	log.Fatal(http.ListenAndServe(":8080", r))
}
