definitions:
  handler.CreateTargetRequest:
    properties:
      interval:
        type: integer
      name:
        type: string
      url:
        type: string
    type: object
  handler.UptimeResponse:
    properties:
      duration:
        type: integer
      status:
        type: string
      status_code:
        type: integer
      url:
        type: string
    type: object
  model.Target:
    properties:
      created_at:
        type: string
      id:
        type: string
      interval:
        type: integer
      name:
        type: string
      url:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /targets:
    get:
      consumes:
      - application/json
      description: Retrieve all uptime monitoring targets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Target'
            type: array
        "500":
          description: Failed to fetch targets
          schema:
            type: string
      summary: Get all targets
      tags:
      - targets
    post:
      consumes:
      - application/json
      description: Create a new uptime monitoring target
      parameters:
      - description: Target payload
        in: body
        name: target
        required: true
        schema:
          $ref: '#/definitions/handler.CreateTargetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Target'
        "400":
          description: Missing or invalid fields
          schema:
            type: string
        "500":
          description: Failed to save target
          schema:
            type: string
      summary: Create a new target
      tags:
      - targets
  /uptime:
    get:
      consumes:
      - application/json
      description: Checks the uptime of a given website URL
      parameters:
      - description: Website URL to check
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.UptimeResponse'
        "400":
          description: Missing url parameter
          schema:
            type: string
      summary: Check website uptime
      tags:
      - uptime
  /users:
    get:
      consumes:
      - application/json
      description: get user by ID
      parameters:
      - description: User ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Invalid id
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
      summary: Get a user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create user with given payload
      parameters:
      - description: User payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: User created
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Failed to create user
          schema:
            type: string
      summary: Create a user
      tags:
      - users
swagger: "2.0"
